### ISSUE TITLE
Hikvision error: Cannot initialize hikvision_next. Error is 'str' object has no attribute 'get'. HA version  2024.10.1

### ISSUE THREAD

**Issue by jamesngob** [maciej-or/hikvision_next#214]
After HA upgrade to 2024.10.1, my Hikvison NVR crashed. The error message is "Cannot initialize hikvision_next. Error is 'str' object has no attribute 'get'."
I have tried to remove the Hikvision integration, restart the HA, re-add the Hikvision integration, still doesn't work
Anyone has the same issue, and perhaps how to fix it? Or any work-around?
Thank you very much

**Comment by redpis** [comment]
I have the same issue.

**Comment by znack14** [comment]
I have the same issue.

**Comment by ON4AHV** [comment]
Same issue

**Comment by jzrinski** [comment]
Ditto.

**Comment by dan-s-github** [comment]
got this after updating to 2024.10.2 and it worked fine with 2024.10.1

I did update the firmware of the nvr and cameras in the mean time

**Comment by jamesngob** [comment]
HA upgraded to 2024.10.2 doesn't help as well in my case. It shows the same error
My NVR firmware is latest

**Comment by dan-s-github** [comment]
just to be clear this issue started on my system after update to 2024.10.2

**Comment by jamesngob** [comment]
Yep, understood. I just tried my luck with 2024.10.2 to see if it works for me, as it worked for you in 2024.10.1 but not for me
:)

**Comment by dan-s-github** [comment]
might be related to the NVR firmware update

my NVR:
![image](https://github.com/user-attachments/assets/dfb10bfb-8306-496e-8ec1-86525367b41e)

**Comment by jzrinski** [comment]
Just rolled back to 2024.10.1 and camera's still have same error !
It only stopped working after 2024.10.2 initially.

**Comment by jamesngob** [comment]
The cache may log the error or something...

**Comment by dan-s-github** [comment]
this seems to be the related section in my ha.log
```
2024-10-13 08:26:39.254 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f4eb85f50>,) inside the event loop by custom integration 'hikvision_next' at custom_components/hikvision_next/isapi.py, line 784: response = await self.isapi.common_request(method, full_url, present, self.isapi.timeout, **data) (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/maciej-or/hikvision_next/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_next/__init__.py", line 55, in async_setup_entry
    await isapi.get_hardware_info()
  File "/config/custom_components/hikvision_next/isapi.py", line 208, in get_hardware_info
    await self.get_device_info()
  File "/config/custom_components/hikvision_next/isapi.py", line 193, in get_device_info
    hw_info = (await self.request(GET, "System/deviceInfo")).get("DeviceInfo", {})
  File "/config/custom_components/hikvision_next/isapi.py", line 784, in request
    response = await self.isapi.common_request(method, full_url, present, self.isapi.timeout, **data)

```

**Comment by maciej-or** [comment]
hi all,
I get the same after upgrading HA to 2024.10.2.
Temporary workaround is to downgrade to 2024.10.1, clear browser cache and restart HA again.
I found the culprit https://developers.home-assistant.io/docs/asyncio_blocking_operations and working on solution.

**Comment by HomeAssist87** [comment]
Same issue here after upgrading HA id the developer working on a fix ?

**Comment by bjoerg560** [comment]
I have the same problem....

**Comment by MusaedQ8** [comment]
same here

**Comment by tpieczka** [comment]
Its working now after today update..

**Comment by ajguerre1** [comment]
> Its working now after today update..

Which update?

**Comment by tpieczka** [comment]
![image](https://github.com/user-attachments/assets/d9c5b275-4e23-4191-ba62-6cba00bda6e7)

**Comment by tpieczka** [comment]
> I have the exact same version but the error still exists, did you do anything else to get it working?
No, update only

**Comment by dan-s-github** [comment]
I can confirm that the supervisor update including restart fixed the issue

**Comment by MusaedQ8** [comment]
Supervisor update then restart 
work well

**Comment by jamesngob** [comment]
I can confirm that Hikvision update to version 1.0.18 fix the issue in HA 2004.10.2
Thank you very much!

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.18

**Comment by HomeAssist87** [comment]
Try clearing your front end cache bestDomenic Sent from my iPhoneOn Oct 15, 2024, at 4:16 AM, redpis ***@***.***> wrote:﻿
Done it, needed a restart 😊
