### ISSUE TITLE
unable to load camera / setup camera with 1.0.9

### ISSUE THREAD

**Issue by weitzelb** [maciej-or/hikvision_next#85]
Hi. After updating to 1.0.9 my already setup camera didn't load anymore. I completely removed the integration. Restarted. Re-installed the integration and then restarted again before attempting another camera setup.

Upon submitting the configuration it loads for a while and then writes an error in the logfile.

> 2023-07-05 11:48:10.139 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://hof.mine.de/ISAPI/System/deviceInfo {....}
2023-07-05 11:48:10.620 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://hof.mine.de/ISAPI/System/capabilities {.....}
2023-07-05 11:48:10.715 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://hof.mine.de/ISAPI/Event/notification/httpHosts {....}
2023-07-05 11:48:10.715 DEBUG (MainThread) [custom_components.hikvision_next.isapi] Alarm Server: AlarmServer(ipAddress='192.168.X.X', portNo=8123, url='/api/hikvision', protocolType='HTTP')
2023-07-05 11:48:10.810 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://hof.mine.de/ISAPI/ContentMgmt/Storage [{'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver10/XMLSchema', '@size': '8'}]
2023-07-05 11:48:10.810 ERROR (MainThread) [custom_components.hikvision_next.config_flow] Unexpected exception 'NoneType' object has no attribute 'get'

**Comment by kint3x** [comment]
Backing that error. 
Unknown error connecting to http://192.168.1.100. Cannot initialize hikvision_next. Error is 'NoneType' object has no attribute 'get'

**Comment by weitzelb** [comment]
Please refer to RP #87.
Problem seems related to cameras without storage (like mine). Like shown in the PR the call to _http://hof.haus.weitzel.xyz/ISAPI/ContentMgmt/Storage_ does not contain any element "hdd". Added a check to prevent further execution and instead return an empty list straight away.

**Comment by digidi** [comment]
Same thing here. Update broke previously working configuration. 1.0.8, 1.0.9 don't work. 1.0.5 works flawlessly
