### ISSUE TITLE
Issue upgrading to v1.0.6

### ISSUE THREAD

**Issue by philr40** [maciej-or/hikvision_next#60]
I've been using the hikvision integration for around 6 months and everything has been working well until attempting to upgrade from v1.0.5 to v1.0.6, after which all of the hikvision switches and sensors became unavailable. 

The logger reports the following error:

Logger: homeassistant.config_entries
Source: config_entries.py:429
First occurred: 17:39:51 (1 occurrences)
Last logged: 17:39:51

Config entry 'Network Video Recorder' for hikvision_next integration not ready yet: Unknown error connecting to http://192.168.xx.xx. Cannot initialize hikvision_next. Error is 'list' object has no attribute 'get'; Retrying in background

My HIK system comprises of a DS-7608NI-I2/8P Network Video Recorder with several cameras (DS-2CD2387G2P-LSU/SL and DS-2CD2387G2-LSU/SL cameras) connected via the NVR. The NVR and cameras are all running the latest firmware, and as mentioned were working ok with the previous v1.0.5 integration. 

After upgrading The integration page shows the hikvision integration in a continuous state of 'retrying setup'.

![hikvision error](https://github.com/maciej-or/hikvision_next/assets/127542571/424c6faa-1464-4b6a-a010-09cb7b5b6461)

I've attempted to delete and reinstall the integration from scratch but get the same error when adding the integration, e.g. it fails to during the setup.

Have restored everything back to v.1.0.5 and its all working again but would be great to get the new version working if possible.

Lastly just wanted to say a big thank you for creating this integration as its made the Hikvision cameras (which are superb) much more useable in domestic installations.

**Comment by msp1974** [comment]
I think this is the same as #45 and #34 which is fixed by the update to the HDD sensor code already in the main branch

**Comment by philr40** [comment]
Hi, I've upgraded to v1.0.7 but unfortunately it still gets stuck in a continuous state of retying the setup.

2023-07-04 08:11:39.772 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Network Video Recorder' for hikvision_next integration not ready yet: Unknown error connecting to http://192.168.xxx.xxx. Cannot initialize hikvision_next. Error is 'list' object has no attribute 'get'; Retrying in background

**Comment by philr40** [comment]
Thanks, v1.0.9 seems to have resolved the problem and everything is working ok again.
